name: Deploy ServerMCP to Azure - Updated Credentials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: beverages-ai
  AZURE_WEBAPP_PACKAGE_PATH: './ServerMCP'
  DOTNET_VERSION: '9.0.x'
  AZURE_RESOURCE_GROUP: lab-AH

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'

    - name: Publish ServerMCP project directly
      run: |
        dotnet publish ServerMCP/ServerMCP.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish